{% set name = "pydicom" %}
{% set version = "1.4.0" %}
{% set sha256 = "48a5b9fa63b45af58c60ddead854218ac4f927f97770e29a28ba7998c4b9dcd8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pydicom/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - pydicom

about:
  home: http://github.com/pydicom/pydicom
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure python package for DICOM medical file reading and writing'
  description: |
    pydicom is a pure python package for parsing DICOM files. DICOM is a
    standard (http://medical.nema.org) for communicating medical images and
    related information such as reports and radiotherapy objects.  pydicom
    makes it easy to read these complex files into natural pythonic structures
    for easy manipulation. Modified datasets can be written again to DICOM
    format files. See the `Getting Started
    <https://pydicom.giathub.io/pydicom/stable/getting_started.html>`_ page for
    installation and basic information, and the `Pydicom User Guide
    <https://pydicom.giathub.io/pydicom/stable/getting_started.html>`_ page for
    an overview of how to use the pydicom library.
  doc_url: https://pydicom.github.io/pydicom
  dev_url: https://github.com/pydicom/pydicom

extra:
  recipe-maintainers:
    - glemaitre
    - darcymason
    - arokem
