{% set name = "pydicom" %}
{% set version = "3.0.1" %}
{% set sha256 = "848ae8e36f34750cf837e48ca5cdf6f7a472145724946d5f28f529279fe11f4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pydicom/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - flit-core

  run:
    - python >=3.10

test:
  imports:
    - pydicom
  requires:
    - flit-core

about:
  home: http://github.com/pydicom/pydicom
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python package for DICOM medical file reading and writing
  description: |
    pydicom is a pure python package for parsing DICOM files. DICOM is a
    standard (https://dicomstandard.org) for communicating medical images and
    related information such as reports and radiotherapy objects.  pydicom
    makes it easy to read these complex files into natural pythonic structures
    for easy manipulation. Modified datasets can be written again to DICOM
    format files. See the `Getting Started
    <https://pydicom.github.io/pydicom/stable/>`_ page for
    installation and basic information, and the `Pydicom User Guide
  doc_url: https://pydicom.github.io/pydicom
  dev_url: https://github.com/pydicom/pydicom

extra:
  recipe-maintainers:
    - mrbean-bremen
    - scaramallion
    - darcymason
    - glemaitre
    - arokem
